//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mondiland.EFModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMenu
    {
        public int id { get; set; }
        public int group_id { get; set; }
        public int menu_id { get; set; }
        public System.Guid lastamp { get; set; }
    
        public virtual GroupInfo GroupInfo { get; set; }
        public virtual MenuInfo MenuInfo { get; set; }
    }
}
