//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mondiland.EFModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuInfo
    {
        public MenuInfo()
        {
            this.GroupMenu = new HashSet<GroupMenu>();
            this.UserMenuFavorites = new HashSet<UserMenuFavorites>();
        }
    
        public int id { get; set; }
        public string menu_name { get; set; }
        public int menu_bmp { get; set; }
        public string menu_window { get; set; }
        public int menu_parent { get; set; }
        public string menu_memo { get; set; }
        public int menu_order { get; set; }
        public System.Guid lastamp { get; set; }
    
        public virtual ICollection<GroupMenu> GroupMenu { get; set; }
        public virtual ICollection<UserMenuFavorites> UserMenuFavorites { get; set; }
    }
}
