//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeClass
    {
        public SizeClass()
        {
            this.PartName = new HashSet<PartName>();
            this.SizeData = new HashSet<SizeData>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
        public string memo { get; set; }
        public System.Guid lastamp { get; set; }
    
        public virtual ICollection<PartName> PartName { get; set; }
        public virtual ICollection<SizeData> SizeData { get; set; }
    }
}
