//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mondiland.EFModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierF
    {
        public int id { get; set; }
        public int supplier_id { get; set; }
        public string address { get; set; }
        public string contacts { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string memo { get; set; }
        public System.Guid lastamp { get; set; }
    
        public virtual SupplierM SupplierM { get; set; }
    }
}
